kind: pipeline
type: docker
name: default

steps:
- name: terraform-lint
  image: hashicorp/terraform:1.4.5
  when:
    branch: main
  commands:
    - "terraform fmt -diff -check -recursive"

- name: terraform-init
  image: hashicorp/terraform:1.4.5
  when:
    branch: main
  commands:
    - "terraform init"

- name: terraform-plan
  image: hashicorp/terraform:1.4.5
  secrets: [ metal_auth_token, project_name ]
  environment:
    METAL_AUTH_TOKEN:
      from_secret: metal_auth_token
    TF_VAR_project_name:
      from_secret: project_name
  when:
    branch: main
  commands:
    - "terraform plan"
---
kind: signature
hmac: 6a3ad01dab6fe8667b011916dab5d23c95e5aa4a8990ba6299e005905b88972a
